### ISSUE TITLE
File changed when opened read-only

### ISSUE THREAD

**Issue by PLatCIC** [SoarGroup/VisualSoar#21]
I opened a VisualSoar project in read-only mode. After I had closed VisualSoar GitHub reported the following changes in the comments.dm file:

![image](https://github.com/SoarGroup/VisualSoar/assets/107441581/726a327a-275e-4137-bdb2-d1bcf0e43fcc)

I'm discarding these changes that should not have been made, and I assume that will not affect the project in other ways.

The image also shows a change in line endings from 'LF' to 'CRLF'. I'm working on Windows, where 'CRLF' is the standard. Does VisualSoar change these? It would be nice if it used the convention for whatever OS it is running on.

**Comment by garfieldnate** [comment]
Regarding the line endings, there is a git setting that lets you check out files with CRLF but then always commit them with LF. I don't really like that, personally, because I want to work with exactly what's in the repo. Unless you use this setting, though, you're asking for two opposite things: don't create changes in Git when using read-only mode, but also change the line endings to match the current system.

**Comment by garfieldnate** [comment]
To clarify: my position on the line endings is that VisualSoar should make a choice of line endings to use in its files and then use that *on all platforms*. The line endings should not be dependent on the platform, as that causes needless changes, and the files are not designed to be directly edited by a user, anyway.

**Comment by PLatCIC** [comment]
I have two comments on what Nathan has said. First, this issue is about changing files when a project was opened read only. That should never happen, and that is the point of this issue. Second, line endings is really a different subject and should be made a separate issue here.

For future reference, I disagree with Nathan on line endings. First of all, most of the files in a VS project are .soar files, which users certainly edit a lot. My preference is to always keep the files with line endings appropriate to the local system so they can be processed with other tools as well.

**Comment by johnlaird** [comment]
I have to go with Nate on line endings. We expect people to work on .soar files on different platforms. There might be the one it is developed on, but that shouldn't be considered special for GIT.

**Comment by PLatCIC** [comment]
Just noted a new aspect: Opened a project, looked at some files, did not change anything or save anything, and closed the project. the <project>.vsa~ file has been touched, it has the current date and time. I don't know if its content was changed.

**Comment by amnuxoll** [comment]
I think the .vsa~ file behavior is as designed?  Visual Soar tries to auto-save content in-case of a crash so you can recover lost changes.  I probably should disable auto-save functionality in read-only mode but I think we should keep the vsa~ updates in regular mode.  Agree/disagree?

**Comment by PLatCIC** [comment]
I think they may be helpful in regular mode, but I believe in read-only mode nothing should ever be touched.

**Comment by PLatCIC** [comment]
I noticed again that after opening in read-only mode Visual Soar touched the .vsa without changing it and created a new .vsa~. In read-only mode neither of these should happen. In addition, in regular mode if a ~ file is needed, I think it should be deleted whenever the project is saved.

**Comment by amnuxoll** [comment]
I've no doubt this is happening.  It's on my to-fix list.

**Comment by johnlaird** [comment]
Sounds like we need a preference as to whether ~ files should be kept. For users without version control, they can be useful, but it seems they are annoying to those who use version control.
________________________________

**Comment by amnuxoll** [comment]
I'm happy to go either way.  If we want to have our cake and eat it too I can add a switch to the Preference menu to toggle it on or off.

**Comment by PLatCIC** [comment]
My suggestion is that the ~ files are needed when things are being edited, but once a file has been saved the ~ version can be deleted.

**Comment by amnuxoll** [comment]
This is fine with me.  I need JEL to make the final call.

**Comment by johnlaird** [comment]
Let’s delete them when editing is done.
________________________________

**Comment by johnlaird** [comment]
I guess when a file is saved.
________________________________

**Comment by amnuxoll** [comment]
I've fixed this bug via a trio of functionality changes.  See more details in [this commit](https://github.com/SoarGroup/VisualSoar/commit/660052b6c8ad914bca5d172540d16a50bcb1c1bb).

**Comment by PLatCIC** [comment]
Tried testing this with the version that calls itself Version 4.6.18 (16 Mar 2024) which was received today, 16 May. Note that the previous version I had called itself Version 4.6.17 (17 Mar 2024).

When I opened a project in read-only mode, I never saw any files get changed. A .vsa~ file was created, although this seems unnecessary in read-only mode, but it was nicely deleted when I closed the project. That is the good news.

There is some bad news as well:

1. The next time I opened VS it had that same project open already, and not in read-only mode! That is dangerous!
2. In the process of doing that, it created a .cfg file in the project folder that was empty. That causes the project folder to get touched and have a new time stamp.
3. The worst news is that when I did reopen the project in read-only mode, it is so read-only that I can't open any file to see the code inside it. There's not much point in opening the project at all if I can't read the code. Read-only should mean no writes but still allow reads.

Clearly more work is needed here. I'll look at #20 as well, and leave comments there.

**Comment by PLatCIC** [comment]
I just noticed that when I run Visual Soar again and it opens that some project not in read-only mode, I still can't open any files to see what's inside.

**Comment by johnlaird** [comment]
Peter,
 I recommend you back off a bit in the tone of these messages.
People (Andy) are doing the best that they can. This comes off as a bit alarmist and critical.

John
________________________________

**Comment by PLatCIC** [comment]
OK, sorry about that. Andy, I appreciate the hard work you're doing on this.

**Comment by amnuxoll** [comment]
Peter, I am grateful that you're giving this a shakedown.  Let me address your points.

0.  Wrong month on version.  My bad.  I was quickly generating a .jar to let you and John pre-test a couple bugs and was careless.  I'm glad we did it though as you turned up a some issues that I can fix before the Soar Workshop.

1.  Reopened project no longer read only:  I never considered this danger.  This is inadvertently as designed.  VS attempts to re-open whatever project you had last time and does not remember whether that project was read only or not.  To fix it, I'd need to remember not only what projects were opened recently but what "mode" they were in.  That's too big of a scope for a quick fix, so I'll open a new issue and let John set the priority for it.

2. The new .cfg file.  This is a necessary addition to VS projects so that it can remember what files you had open for a given project.  I can't store this info with the VS preferences because it's project-specific.  Going forward, future project-specific preferences (e.g., whether it should be loaded read-only or not) will need to placed here too.  I think the right "solution" here is to put the .cfg file into your .gitignore

3. Can't view files.  This one has me scratching my head as I'm unable to recreate it on my end.  I wonder, are you seeing any sort of crash report on the command line when it fails to open a file?

**Comment by PLatCIC** [comment]
We're making progress! My comments.

0. Don't worry about it. I just wanted you to know.
1. Before this version I never saw VS automatically open a previously open project. What it did do was point to the previous folder when I asked it to open a project. That way I have the choice of whether to open read-only or not.
2. I sounds like this is part of a new feature where VS tries to restore the view you had when you last closed your project without any manual intervention. That's fine, as long as it remembers whether to do read-only or not. Perhaps that could be stored in the .cfg file.
3. With this new version, I have never been able to open any file. If I double click on the file name or right click on it and then click on Open Rules, either way nothing at all happens. I don't normally run it from a command line, but when I did that I saw no error messages. It is just completely locked up. I tried it on a different project and it did the same thing.

**Comment by johnlaird** [comment]
A few comments (in order of importance).

  1.
Andy: I have the same problem as Peter in that once I open a project I cannot open any files. I can expand folders, but nothing happens when I double click on the file name.
  2.
Peter: Yes, part of this release is that Visual Soar will remember your tiling and the last project you worked on. That is a huge win for me. There is the negative interaction with read-only mode in that you will have to remember to switch to read only. I'm not going to tell Andy to pursue the fix he mentioned as his estimate makes it sounds like it could be expensive. I wonder if it would be faster for him to add an option in the preferences as to whether VS automatically opens the last file. That would at least put you back to the previous version and force you to open it (where you would do it by read only). Comments?



________________________________

**Comment by amnuxoll** [comment]
I'm re-opening this issue due to the "can't open rules files" problem.

**Comment by amnuxoll** [comment]
The "can't open rules files" problem was unrelated to this issue.  So, I'll create a separate issue to track it.  (Also, btw, it's fixed.)
